version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ypathan
      POSTGRES_PASSWORD: nokian876
      POSTGRES_DB: library
    ports:
      - "6900:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: